services:
  - type: web
    name: esteira-demandas
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: esteira-demandas-db
          property: connectionString

databases:
  - name: esteira-demandas-db
    plan: free
